### PR TITLE
Show related image of blog post if defined

### PR DESCRIPTION
**Pull request by flortsch**
This PR changes the home and post layouts to include a related blog post image if defined. An example can be seen on my site: https://florian-latifi.at

### CODE REVIEW

**Comment by yous** [comment]
I think this can be done by adding an image to the top of the post. Have a look at [an example post](https://yous.be/2018/12/02/how-to-open-binary-plist-files-using-vim-plist/) and [its source](https://github.com/yous/yous.be/blob/source/_posts/2018-12-02-how-to-open-binary-plist-files-using-vim-plist.markdown).

**Comment by flortsch** [comment]
Oh, I totally forgot that this is also possible in markdown, which is also much simpler, if the image does not require any styling. Well, I thought too complicated then :D

**Comment by yous** [comment]
No problem. Also you can use some HTML tags in markdown directly, for example, to align some images.
``` markdown
<p align="center">
  <img src="/path/to/image" />
</p>
```

**Comment by flortsch** [comment]
With, e.g., kramdown, you can actually make use of some custom markdown features and directly specify styling options for given elements. For example, to center an image and give it round corners:
```
{:style="text-align:center"}
![Profile picture](/assets/profile.png "Me"){:style="border-radius:50%"}
```
Note that the first style definition has to be on the above line, so the image is wrapped into a paragraph, in order for the text-align to work. I used this, to put a picture at the beginning of my resume. With this, layout adjustments for other use-cases might also be avoided. Maybe it helps someone :)

**Pull request closed without merging**
